MESSAGE("*********************************************")
MESSAGE("CMAKE VERSION: ${CMAKE_VERSION}")
MESSAGE("CMAKE_GENERATOR: ${CMAKE_GENERATOR}")
MESSAGE("CMAKE_CXX_COMPILER_ID: ${CMAKE_CXX_COMPILER_ID}")
MESSAGE("CMAKE_CXX_COMPILER: ${CMAKE_CXX_COMPILER}")
MESSAGE("CMAKE_C_COMPILER_ID: ${CMAKE_C_COMPILER_ID}")
MESSAGE("CMAKE_C_COMPILER: ${CMAKE_C_COMPILER}")
MESSAGE("CMAKE_ASM_MASM_COMPILER: ${CMAKE_ASM_MASM_COMPILER}")
MESSAGE("CMAKE_ASM_COMPILER: ${CMAKE_ASM_COMPILER}")
MESSAGE("CMAKE_MAKE_PROGRAM: ${CMAKE_MAKE_PROGRAM}")
MESSAGE("CMAKE_SYSTEM_NAME: ${CMAKE_SYSTEM_NAME}")
MESSAGE("CMAKE_SYSTEM_VERSION: ${CMAKE_SYSTEM_VERSION}")
MESSAGE("CMAKE_SYSTEM_PROCESSOR: ${CMAKE_SYSTEM_PROCESSOR}")
MESSAGE("CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE}")
MESSAGE("CMAKE_SIZEOF_VOID_P: ${CMAKE_SIZEOF_VOID_P}")
MESSAGE("*********************************************")
MESSAGE("CMAKE_SOURCE_DIR: ${CMAKE_SOURCE_DIR}")
MESSAGE("CMAKE_BINARY_DIR: ${CMAKE_BINARY_DIR}")
MESSAGE("*********************************************")

SET(CMAKE_TEMP_DIR ${CMAKE_BINARY_DIR}/solutions)

IF(CMAKE_SIZEOF_VOID_P EQUAL 4)
    SET(DAZZLE_ARCHITECTURE_X86 ON CACHE BOOL "DAZZLE_ARCHITECTURE_X86" FORCE)
    SET(DAZZLE_ARCHITECTURE_X64 OFF CACHE BOOL "DAZZLE_ARCHITECTURE_X64" FORCE)
ELSEIF(CMAKE_SIZEOF_VOID_P EQUAL 8)
    SET(DAZZLE_ARCHITECTURE_X86 OFF CACHE BOOL "DAZZLE_ARCHITECTURE_X86" FORCE)
    SET(DAZZLE_ARCHITECTURE_X64 ON CACHE BOOL "DAZZLE_ARCHITECTURE_X64" FORCE)
ELSE()
    message(FATAL_ERROR "unsupport CMAKE_SIZEOF_VOID_P")
ENDIF()

MESSAGE("DAZZLE_ARCHITECTURE_X86: ${DAZZLE_ARCHITECTURE_X86}")
MESSAGE("DAZZLE_ARCHITECTURE_X64: ${DAZZLE_ARCHITECTURE_X64}")

IF(DAZZLE_ARCHITECTURE_X86)
    SET(DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX "x86")
ELSEIF(DAZZLE_ARCHITECTURE_X64)
    SET(DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX "x64")
ELSE()
    MESSAGE(FATAL_ERROR "unsupported architecture") 
ENDIF()

set_property(GLOBAL PROPERTY USE_FOLDERS ON)

SET(DAZZLE_REPOSITORY ${CMAKE_CURRENT_SOURCE_DIR}/../..)

IF(NOT DAZZLE_INSTALL_PATH)
    SET(DAZZLE_INSTALL_PATH ${DAZZLE_REPOSITORY}/bin)
ENDIF()

MESSAGE("DAZZLE_INSTALL_PATH: ${DAZZLE_INSTALL_PATH}")

IF(NOT DAZZLE_PDB_PATH)
    SET(DAZZLE_PDB_PATH ${DAZZLE_REPOSITORY}/pdb)
ENDIF()

MESSAGE("DAZZLE_PDB_PATH: ${DAZZLE_PDB_PATH}")

IF(CMAKE_GENERATOR_PLATFORM)
    SET(DAZZLE_THIRDPARTY_LIB_OUT "${DAZZLE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR} ${CMAKE_GENERATOR_PLATFORM}/${DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX}")
    SET(DAZZLE_THIRDPARTY_CONFIG_OUT "${DAZZLE_REPOSITORY}/dependencies/configuration/${CMAKE_GENERATOR} ${CMAKE_GENERATOR_PLATFORM}/${DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX}")
ELSE()
    SET(DAZZLE_THIRDPARTY_LIB_OUT "${DAZZLE_REPOSITORY}/lib/dependencies/${CMAKE_GENERATOR}/${DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX}")
    SET(DAZZLE_THIRDPARTY_CONFIG_OUT "${DAZZLE_REPOSITORY}/dependencies/configuration/${CMAKE_GENERATOR}/${DAZZLE_THIRDPARTY_ARCHITECTURE_SUFFIX}")
ENDIF()

SET(DAZZLE_THIRDPARTY_DIR ${DAZZLE_REPOSITORY}/dependencies)

MESSAGE("UNIX: ${UNIX}")
MESSAGE("ANDROID: ${ANDROID}")
MESSAGE("MINGW: ${MINGW}")
MESSAGE("WIN32: ${WIN32}")
MESSAGE("APPLE: ${APPLE}")
MESSAGE("IOS: ${IOS}")

if(UNIX AND NOT ANDROID AND NOT APPLE AND NOT IOS)
    # input and thirdparty paths
    SET(DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX ${CMAKE_BUILD_TYPE})
elseif(ANDROID)
    # input and thirdparty paths
    SET(DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX ${CMAKE_BUILD_TYPE}/${ANDROID_ABI})
elseif(MINGW)
    # input and thirdparty paths
    SET(DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX ${CMAKE_BUILD_TYPE})
elseif(APPLE)
    # input and thirdparty paths
    SET(DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX ${CMAKE_BUILD_TYPE})
else()
    # input and thirdparty paths
    SET(DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX ${CMAKE_BUILD_TYPE})
endif()

SET(DAZZLE_THIRDPARTY_LIB_DIR ${DAZZLE_THIRDPARTY_LIB_OUT}/${DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX})
SET(DAZZLE_THIRDPARTY_CONFIG_DIR ${DAZZLE_THIRDPARTY_CONFIG_OUT}/${DAZZLE_THIRDPARTY_LIB_OUT_SUFFIX})

MESSAGE("DAZZLE_THIRDPARTY_DIR: ${DAZZLE_THIRDPARTY_DIR}")
MESSAGE("DAZZLE_THIRDPARTY_LIB_DIR: ${DAZZLE_THIRDPARTY_LIB_DIR}")
MESSAGE("DAZZLE_THIRDPARTY_CONFIG_DIR: ${DAZZLE_THIRDPARTY_CONFIG_DIR}")

SET(DAZZLE_CMAKE_DEPENDENCIES_DIR ${DAZZLE_REPOSITORY}/cmake/dependencies)
SET(DAZZLE_SOURCE_DIR ${DAZZLE_REPOSITORY}/src)
SET(DAZZLE_INCLUDE_DIR ${DAZZLE_REPOSITORY}/include)
SET(DAZZLE_DEPENDENCIES_DIR ${DAZZLE_REPOSITORY}/dependencies)
SET(DAZZLE_TOOLS_DIR ${DAZZLE_REPOSITORY}/tools)

MESSAGE("DAZZLE_CMAKE_DEPENDENCIES_DIR: ${DAZZLE_CMAKE_DEPENDENCIES_DIR}")
MESSAGE("DAZZLE_SOURCE_DIR: ${DAZZLE_SOURCE_DIR}")
MESSAGE("DAZZLE_INCLUDE_DIR: ${DAZZLE_INCLUDE_DIR}")
